# Generated by Django 3.2.8 on 2021-10-15 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория Мебели')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория комнаты')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Мебель')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('category_furniture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_furniture', to='hotel_room.categoryfurniture', verbose_name='Категория Мебели')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер комнаты')),
                ('img', models.ImageField(blank=True, upload_to='room', verbose_name='Фото комнаты')),
                ('count_windows', models.IntegerField(verbose_name='Количество Окан')),
                ('slug', models.SlugField(max_length=255, verbose_name='Слаг')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_room.categoryroom', verbose_name='Категория комнаты')),
                ('furniture', models.ManyToManyField(to='hotel_room.Furniture', verbose_name='Мебель')),
            ],
        ),
    ]
