# Generated by Django 3.2.8 on 2021-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
