# Generated by Django 3.2.8 on 2021-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_bevor',
            field=models.DateField(verbose_name='до какого числа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_from',
            field=models.DateField(verbose_name='С какого числа'),
        ),
    ]
