# Generated by Django 3.2.8 on 2021-10-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_room', '0002_room_price'),
        ('book', '0003_auto_20211016_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel_room.room', verbose_name='Номер'),
        ),
    ]
